xwiki/xwiki-commons

- xwiki-commons-core/xwiki-commons-extension/xwiki-commons-extension-api/src/test/java/org/xwiki/extension/test/TestExtensionHandler.java
- xwiki-commons-core/xwiki-commons-extension/xwiki-commons-extension-handlers/xwiki-commons-extension-handler-jar/src/main/java/org/xwiki/extension/jar/internal/handler/JarExtensionHandler.java
There was a few deprecated used of `@Component("something")` instead of 
```
@Component
@Named("something")
```
> Fix the deprecated uses of @Component

- xwiki-commons-core/xwiki-commons-logging/xwiki-commons-logging-api/src/main/java/org/xwiki/logging/internal/helpers/MessageParser.java
- xwiki-commons-core/xwiki-commons-script/src/test/java/org/xwiki/script/internal/safe/DefaultScriptSafeProviderTest.java
- xwiki-commons-core/xwiki-commons-xml/src/main/java/org/xwiki/xml/ExtractHandler.java
- xwiki-commons-core/xwiki-commons-xml/src/main/java/org/xwiki/xml/Sax2Dom.java
This PR is being created because of a new violation found in CheckStyle's regression of XWiki.
PR: https://github.com/checkstyle/checkstyle/pull/3189#issuecomment-220032301
While doing a cleanup of multiple Checks, it was found out that `IllegalInstantiationCheck` was not working correctly if the there was a space between different classes in the property for the configuration file. With the new fix, we caused violations like the below:
````[ERROR] /home/travis/build/checkstyle/checkstyle/xwiki-commons/xwiki-commons-core/xwiki-commons-xml/src/main/java/org/xwiki/xml/Sax2Dom.java:152:33: Instantiation of java.lang.String should be avoided. [IllegalInstantiation]````
You can either accept this PR and not have an issue when you upgrade CS with this fix in the future,
or make your own …
> [Misc] Fix violations for bug in 'IllegalInstantiationCheck'

- xwiki-commons-tools/xwiki-commons-tool-verification-resources/src/main/java/org/xwiki/tool/checkstyle/ComponentAnnotationCheck.java
- xwiki-commons-tools/xwiki-commons-tool-verification-resources/src/main/java/org/xwiki/tool/checkstyle/ScriptServiceCheck.java
- xwiki-commons-tools/xwiki-commons-tool-verification-resources/src/main/java/org/xwiki/tool/checkstyle/SinceFormatCheck.java
- xwiki-commons-tools/xwiki-commons-tool-verification-resources/src/main/java/org/xwiki/tool/checkstyle/UnstableAnnotationCheck.java
This PR is being created because of a new compilation error found in CheckStyle's regression of XWiki.
PR: https://github.com/checkstyle/checkstyle/pull/4573
Original Issue: https://github.com/checkstyle/checkstyle/issues/605
New Issue: https://github.com/checkstyle/checkstyle/issues/4582
We are breaking multiple APIs in Checkstyle 8 to clean up some bad coding styles. This changed the 2 methods to abstract forcing all Checks to specifically implement their intended behavior for their token handling.
You can either accept this PR and not have an issue when you upgrade CS with this fix in the future,
or make your own change/fix later when you do upgrade CS.
Please let us know which way you intend to go.
Feel free to ask any other questions or propose any additional changes.
Thanks.
> [Misc] Fix abstract method errors in Checkstyle 8

- xwiki-commons-tools/xwiki-commons-tool-verification-resources/pom.xml
Like I mentioned in https://github.com/xwiki/xwiki-commons/pull/17#issuecomment-312504317 , Checkstyle can't resume regression without this exclusion as we get conflicts.
> [WARNING] Rule 0: org.apache.maven.plugins.enforcer.RequireUpperBoundDeps failed with message:
Failed while enforcing RequireUpperBoundDeps. The error(s) are [
Require upper bound dependencies error for com.google.guava:guava:20.0 paths to dependency are:
+-org.xwiki.commons:xwiki-commons-tool-verification-resources:9.6-SNAPSHOT
+-com.puppycrawl.tools:checkstyle:8.0-SNAPSHOT
+-com.google.guava:guava:20.0 (managed) <-- com.google.guava:guava:22.0
and
+-org.xwiki.commons:xwiki-commons-tool-verification-resources:9.6-SNAPSHOT
+-com.puppycrawl.tools:checkstyle:8.0-SNAPSHOT
+-com.google.guava:guava:20.0
> [misc] removed guava dependency from checkstyle

- xwiki-commons-core/xwiki-commons-environment/xwiki-commons-environment-standard/src/main/java/org/xwiki/environment/System.java
replaced getClassLoader() which does not work with J2EE according to sonar. http://sonar.xwiki.org/issues/search#issues=2a3b9a97-4a6d-421f-a152-caf8f453f395
> [codestyle] works with all versions of java

- pom.xml
- xwiki-commons-tools/xwiki-commons-tool-verification-resources/src/main/java/org/xwiki/tool/checkstyle/UnstableAnnotationCheck.java
- xwiki-commons-tools/xwiki-commons-tool-verification-resources/src/test/java/org/xwiki/tool/checkstyle/UnstableAnnotationCheckTest.java
https://jira.xwiki.org/browse/XCOMMONS-1430
Not ready to apply.
PR is triggered to keep checkstyle regression testing over xwiki update.
apply only when 8.11 checkstyle is released (last weekend of June).
> XCOMMONS-1430: update checkstyle to 8.11, checkstyle/checkstyle#5812

- xwiki-commons-tools/xwiki-commons-tool-xar/xwiki-commons-tool-xar-plugin/src/main/java/org/xwiki/tool/xar/AbstractVerifyMojo.java
- xwiki-commons-tools/xwiki-commons-tool-xar/xwiki-commons-tool-xar-plugin/src/main/java/org/xwiki/tool/xar/FormatMojo.java
- xwiki-commons-tools/xwiki-commons-tool-xar/xwiki-commons-tool-xar-plugin/src/main/java/org/xwiki/tool/xar/VerifyMojo.java
- xwiki-commons-tools/xwiki-commons-tool-xar/xwiki-commons-tool-xar-plugin/src/main/java/org/xwiki/tool/xar/internal/XWikiDocument.java
Removing date fields with `xar:format` and failing the build with `xar:verify` if date fields are present in the XML pages.
More details on the previous discussion: https://markmail.org/thread/ymwsebvr3k7voy3p
> XCOMMONS-1447: XAR plugin should replace the dates with a common number

- pom.xml
Related to the answer provided in: https://github.com/STAMP-project/pitest-descartes/issues/72
> chore: Avoid PIT to fail the build if no mutation has been found.

- xwiki-commons-core/xwiki-commons-properties/src/main/java/org/xwiki/properties/PropertyDescriptor.java
- xwiki-commons-core/xwiki-commons-properties/src/main/java/org/xwiki/properties/annotation/PropertyDisplayType.java
- xwiki-commons-core/xwiki-commons-properties/src/main/java/org/xwiki/properties/internal/DefaultBeanDescriptor.java
- xwiki-commons-core/xwiki-commons-properties/src/main/java/org/xwiki/properties/internal/DefaultPropertyDescriptor.java
- xwiki-commons-core/xwiki-commons-properties/src/test/java/org/xwiki/properties/internal/DefaultBeanDescriptorTest.java
- xwiki-commons-core/xwiki-commons-properties/src/test/java/org/xwiki/properties/test/TestBean.java
https://jira.xwiki.org/browse/XCOMMONS-1558
* Introduce a PropertyDisplayType annotation that we can use to specify with which type the macro parameter should be rendered.
* Add the display type in the property descriptor.
The idea is to put the `PropertyDisplayType` annotation on macro parameters and, in the ckeditor application, use the provided type for the input rendering instead of the actual parameter type.
> XCOMMONS-1558: Create a PropertyDisplayType annotation

- xwiki-commons-core/xwiki-commons-xml/src/main/java/org/xwiki/xml/internal/html/DefaultHTMLCleaner.java
- xwiki-commons-core/xwiki-commons-xml/src/test/java/org/xwiki/xml/internal/html/DefaultHTMLCleanerTest.java
https://jira.xwiki.org/browse/XCOMMONS-1571
* Disable trimmed values property in HtmlCleaner
> XCOMMONS-1571: HtmlCleaner strips the leading space in value form attributes

- pom.xml
Identified at checkstyle/checkstyle#7088
Checkstyle is looking to remove some deprecated methods and our CI noticed that you are not on the latest maven-checkstyle-plugin which is still using some deprecated methods.
> upgrade maven-checkstyle-plugin to 3.1.0

- xwiki-commons-tools/xwiki-commons-tool-verification-resources/src/main/resources/checkstyle.xml
https://checkstyle.org/releasenotes.html#Release_8.28
reason: https://github.com/checkstyle/checkstyle/issues/7329
checkstyle project need this update to continue to keep xwiki in checkstyle's CI verification process.
> config: remove deprecated properties from checkstyle's JavadocMethod

- pom.xml
Issue: checkstyle/checkstyle/issues/7190
PR: checkstyle/checkstyle#7778
Checkstyle is planning on removing some deprecated methods, and Checkstyle's CI reported that xwiki-commons isn't on the latest maven-checkstyle-plugin version, and still uses some of the deprecated methods.
> upgrade maven-checkstyle-plugin to 3.1.1

- xwiki-commons-core/xwiki-commons-diff/xwiki-commons-diff-xml/src/main/java/org/xwiki/diff/xml/internal/UnifiedHTMLDiffManager.java
- xwiki-commons-core/xwiki-commons-diff/xwiki-commons-diff-xml/src/test/resources/html/entityReference.test
- xwiki-commons-core/xwiki-commons-xml/pom.xml
- xwiki-commons-core/xwiki-commons-xml/src/main/java/org/htmlcleaner/XWikiDOMSerializer.java
- xwiki-commons-core/xwiki-commons-xml/src/main/java/org/xwiki/xml/html/HTMLCleanerConfiguration.java
- xwiki-commons-core/xwiki-commons-xml/src/main/java/org/xwiki/xml/html/HTMLUtils.java
- xwiki-commons-core/xwiki-commons-xml/src/main/java/org/xwiki/xml/internal/html/DefaultHTMLCleaner.java
- xwiki-commons-core/xwiki-commons-xml/src/test/java/org/xwiki/xml/internal/html/DefaultHTMLCleanerTest.java
* Upgrade to 2.23
* Fix XWikiDOMSerializer to use the right flag to not escape XML in
the produced Document
* Fix a bug in HTMLUtils that prevented the < > to be properly escaped
during serialization
* Refactor HtmlCleanerTest to ensure that the content of the Document
is what expected before serialization. And change some expected HTML
results.
* Introduce a new configuration in HtmlCleanerConfiguration to
translate special HTML entities, to be able to use them in an XML
Parser
* Use the new configuration in UnifiedHTMLDiffManager
* Fix the failing test and clean a bit
> XCOMMONS-1740: Upgrade to HTML Cleaner 2.23

- xwiki-commons-core/xwiki-commons-diff/xwiki-commons-diff-xml/src/main/java/org/xwiki/diff/xml/internal/UnifiedHTMLDiffManager.java
- xwiki-commons-core/xwiki-commons-xml/pom.xml
- xwiki-commons-core/xwiki-commons-xml/src/main/java/org/xwiki/xml/html/HTMLUtils.java
- xwiki-commons-core/xwiki-commons-xml/src/main/java/org/xwiki/xml/internal/html/DefaultHTMLCleaner.java
- xwiki-commons-core/xwiki-commons-xml/src/test/java/org/xwiki/xml/internal/html/DefaultHTMLCleanerTest.java
* Keep as much as possible the entities parsed in the Document
* Since HtmlCleaner doesn't allow to easily parse unicode characters,
keep them translated with their character reference
* Only unescape the &amp; for character references in HtmlUtils
* Remove previous exception made in UnifiedHTMLDiffManager since it's
not needed anymore.
> XCOMMONS-1938: Upgrade to HtmlCleaner 2.24

- xwiki-commons-core/xwiki-commons-job/pom.xml
- xwiki-commons-core/xwiki-commons-job/src/main/java/org/xwiki/job/GroupedJobInitializer.java
- xwiki-commons-core/xwiki-commons-job/src/main/java/org/xwiki/job/GroupedJobInitializerManager.java
- xwiki-commons-core/xwiki-commons-job/src/main/java/org/xwiki/job/JobGroupPath.java
- xwiki-commons-core/xwiki-commons-job/src/main/java/org/xwiki/job/JobManagerConfiguration.java
- xwiki-commons-core/xwiki-commons-job/src/main/java/org/xwiki/job/internal/DefaultGoupedJobInitializer.java
- xwiki-commons-core/xwiki-commons-job/src/main/java/org/xwiki/job/internal/DefaultGroupedJobInitializerManager.java
- xwiki-commons-core/xwiki-commons-job/src/main/java/org/xwiki/job/internal/DefaultJobExecutor.java
- xwiki-commons-core/xwiki-commons-job/src/main/java/org/xwiki/job/internal/DefaultJobManagerConfiguration.java
- xwiki-commons-core/xwiki-commons-job/src/main/java/org/xwiki/job/internal/JobGroupPathLockTree.java
- xwiki-commons-core/xwiki-commons-job/src/main/java/org/xwiki/job/internal/ReadWriteSemaphore.java
- xwiki-commons-core/xwiki-commons-job/src/main/resources/META-INF/components.txt
- xwiki-commons-core/xwiki-commons-job/src/test/java/org/xwiki/job/internal/DefaultGroupedJobInitializerManagerTest.java
- xwiki-commons-core/xwiki-commons-job/src/test/java/org/xwiki/job/internal/DefaultJobExecutorTest.java
* Define a GroupedJobInitializer role whose purpose is to be able to
specify some default configuration for the pool of GroupedJob
* Define a GroupedJobInitializerManager in charge of retrieving the
appropriate GroupedJobInitializer based on a JobGroupPath and to
fallback on parents or default
* Rewrite JobGroupPathLockTree to use read/write semaphores based on
the configured pool size
* Change ThreadPoolExecutor constructors in DefaultJobExecutor to
allow using a pool of more than 1 threads and to allow configuring
the keepAliveTime for the threads
* Provide some new tests to ensures the threads are operating
correctly with a pool > 1 thread
* Create a dedicated class for ReadWriteSemaphore and improve a bit
the semaphore implementation with a lock on readCounter and by
taking into …
> XCOMMONS-1959: Allow to define the pool size of a GroupedJob

- xwiki-commons-core/xwiki-commons-velocity/src/main/java/org/xwiki/velocity/tools/URLTool.java
- xwiki-commons-core/xwiki-commons-velocity/src/test/java/org/xwiki/velocity/tools/URLToolTest.java
The method should return an URL object from a given string if the string is right formatted, otherwise null.
> XCOMMONS-2042: Add a method in URLTool to convert a string in an URL object

- xwiki-commons-core/xwiki-commons-extension/xwiki-commons-extension-repositories/xwiki-commons-extension-repository-maven/src/main/java/org/xwiki/extension/repository/aether/internal/AetherExtensionRepository.java
- xwiki-commons-core/xwiki-commons-extension/xwiki-commons-extension-repositories/xwiki-commons-extension-repository-maven/src/main/java/org/xwiki/extension/repository/aether/internal/XWikiRepositorySystemSession.java
Add support for HTTP headers in the extension repository configuration for Maven repositories
> XCOMMONS-2099 : Allow to define HTTP headers to Maven extension repositories

- xwiki-commons-tools/xwiki-commons-tool-verification-resources/pom.xml
problem detected at https://github.com/checkstyle/checkstyle/pull/9025
but we still have problem to run successfully 
`[ERROR] Failed to execute goal on project xwiki-commons-xml: Could not resolve dependencies for project org.xwiki.commons:xwiki-commons-xml:jar:13.0-SNAPSHOT: Failure to find io.sf.carte:xml-dtd:jar:3.1.0 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal on project xwiki-commons-xml: Could not resolve dependencies for project org.xwiki.commons:xwiki-commons-xml:jar:13.0-SNAPSHOT: Failure to find io.sf.carte:xml-dtd:jar:3.1.0 in …
> [misc] exclude org.antlr dependency from checkstyle

- pom.xml
- xwiki-commons-core/xwiki-commons-context/src/main/java/org/xwiki/context/internal/concurrent/AbstractContextStore.java
- xwiki-commons-tools/xwiki-commons-tool-verification-resources/src/main/resources/checkstyle.xml
From failure at https://travis-ci.org/github/checkstyle/checkstyle/jobs/763584503 in reference to https://github.com/checkstyle/checkstyle/issues/7417
Checkstyle has changed the `scope` property to `accessModifiers` in `JavadocMethodCheck`. This PR will update xwiki's Checkstyle config to accommodate this (breaking) change, which will be included in the next Checkstyle release. When the next Checkstyle version is released, I will rebase this PR and update the Checkstyle version number.
Successful Checkstyle execution with new property on this project: https://travis-ci.org/github/checkstyle/checkstyle/jobs/765159353
> [update] change scope to access modifiers for JavadocMethod in Checkstyle config

- xwiki-commons-core/xwiki-commons-xml/pom.xml
- xwiki-commons-core/xwiki-commons-xml/src/main/java/org/xwiki/xml/XMLUtils.java
- xwiki-commons-core/xwiki-commons-xml/src/test/java/org/xwiki/xml/XMLUtilsTest.java
add custom error listener to overwrite the default error listener which fills the standard output with expected error messages
I did not write unit tests for this, thus the slightly lower coverage.
I feel it to be relatively hard to write a unit test to check this and also e.g. the `warning` method on the error listener might never be called from our code but must be proviced to implement the interface. I hope this is acceptable for a minor issue.
> XCOMMONS-2272: ERROR: 'Length limit reached'

- xwiki-commons-tools/xwiki-commons-tool-verification-resources/src/main/resources/revapi.json
* Add Revapi ignore rule for adding and removing @Unstable-annotations
Jira Issue: https://jira.xwiki.org/browse/XCOMMONS-2313
> XCOMMONS-2313: Revapi should ignore added or removed @Unstable annotations

- xwiki-commons-core/xwiki-commons-diff/xwiki-commons-diff-api/src/main/java/org/xwiki/diff/internal/DefaultDiffManager.java
- xwiki-commons-core/xwiki-commons-diff/xwiki-commons-diff-api/src/test/java/org/xwiki/diff/internal/DefaultDiffManagerIntegrationTest.java
- xwiki-commons-core/xwiki-commons-diff/xwiki-commons-diff-api/src/test/java/org/xwiki/diff/internal/DefaultDiffManagerTest.java
- xwiki-commons-core/xwiki-commons-diff/xwiki-commons-diff-api/src/test/resources/integration2/current.txt
- xwiki-commons-core/xwiki-commons-diff/xwiki-commons-diff-api/src/test/resources/integration2/next.txt
- xwiki-commons-core/xwiki-commons-diff/xwiki-commons-diff-api/src/test/resources/integration2/previous.txt
- xwiki-commons-core/xwiki-commons-diff/xwiki-commons-diff-display/src/main/java/org/xwiki/diff/display/internal/DefaultUnifiedDiffDisplayer.java
- xwiki-commons-core/xwiki-commons-diff/xwiki-commons-diff-display/src/test/java/org/xwiki/diff/display/internal/DefaultUnifiedDiffDisplayerIntegrationTest.java
- xwiki-commons-core/xwiki-commons-diff/xwiki-commons-diff-display/src/test/java/org/xwiki/diff/display/internal/DefaultUnifiedDiffDisplayerTest.java
- xwiki-commons-core/xwiki-commons-diff/xwiki-commons-diff-display/src/test/resources/integration3/current.txt
- xwiki-commons-core/xwiki-commons-diff/xwiki-commons-diff-display/src/test/resources/integration3/next.txt
- xwiki-commons-core/xwiki-commons-diff/xwiki-commons-diff-display/src/test/resources/integration3/previous.txt
- xwiki-commons-core/xwiki-commons-diff/xwiki-commons-diff-display/src/test/resources/integration4/current.txt
- xwiki-commons-core/xwiki-commons-diff/xwiki-commons-diff-display/src/test/resources/integration4/next.txt
- xwiki-commons-core/xwiki-commons-diff/xwiki-commons-diff-display/src/test/resources/integration4/previous.txt
- xwiki-commons-core/xwiki-commons-diff/xwiki-commons-diff-display/src/test/resources/integration5/current.txt
- xwiki-commons-core/xwiki-commons-diff/xwiki-commons-diff-display/src/test/resources/integration5/next.txt
- xwiki-commons-core/xwiki-commons-diff/xwiki-commons-diff-display/src/test/resources/integration5/previous.txt
- xwiki-commons-core/xwiki-commons-diff/xwiki-commons-diff-display/src/test/resources/integration6/current.txt
- xwiki-commons-core/xwiki-commons-diff/xwiki-commons-diff-display/src/test/resources/integration6/next.txt
- xwiki-commons-core/xwiki-commons-diff/xwiki-commons-diff-display/src/test/resources/integration6/previous.txt
- xwiki-commons-core/xwiki-commons-diff/xwiki-commons-diff-display/src/test/resources/integration7/current.txt
- xwiki-commons-core/xwiki-commons-diff/xwiki-commons-diff-display/src/test/resources/integration7/next.txt
- xwiki-commons-core/xwiki-commons-diff/xwiki-commons-diff-display/src/test/resources/integration7/previous.txt
- xwiki-commons-core/xwiki-commons-diff/xwiki-commons-diff-display/src/test/resources/integration8/current.txt
- xwiki-commons-core/xwiki-commons-diff/xwiki-commons-diff-display/src/test/resources/integration8/next.txt
- xwiki-commons-core/xwiki-commons-diff/xwiki-commons-diff-display/src/test/resources/integration8/previous.txt
- xwiki-commons-core/xwiki-commons-diff/xwiki-commons-diff-display/src/test/resources/integration9/current.txt
- xwiki-commons-core/xwiki-commons-diff/xwiki-commons-diff-display/src/test/resources/integration9/next.txt
- xwiki-commons-core/xwiki-commons-diff/xwiki-commons-diff-display/src/test/resources/integration9/previous.txt
[XCOMMONS-2068](https://jira.xwiki.org/browse/XCOMMONS-2068): Possible OutOfBoundsException when performing diff
[XCOMMONS-2137](https://jira.xwiki.org/browse/XCOMMONS-2137): Possible IllegalArgumentException when performing a merge
This changes provides new integration tests that helped investigating
the problems in the diff algorithm. Basically the main issue was in the
creation of conflicts information: all subsequent errors are most likely
coming from there.
The changes here are mostly about computing a proper index for extract
conflict information, and actually enforcing proper usage of sublist API
to avoid problems: this might displays some loggers if other problems
occurs in the algorithm, but this would not break the caller.
Note that the integration tests file are produced using …
> XCOMMONS-2068: Possible OutOfBoundsException when performing diff

- xwiki-commons-core/xwiki-commons-xml/src/main/java/org/xwiki/xml/html/HTMLCleanerConfiguration.java
- xwiki-commons-core/xwiki-commons-xml/src/main/java/org/xwiki/xml/html/HTMLConstants.java
- xwiki-commons-core/xwiki-commons-xml/src/main/java/org/xwiki/xml/internal/html/DefaultHTMLCleaner.java
- xwiki-commons-core/xwiki-commons-xml/src/main/java/org/xwiki/xml/internal/html/FontTagTransformation.java
- xwiki-commons-core/xwiki-commons-xml/src/main/java/org/xwiki/xml/internal/html/filter/BodyFilter.java
- xwiki-commons-core/xwiki-commons-xml/src/main/java/org/xwiki/xml/internal/html/filter/FontFilter.java
- xwiki-commons-core/xwiki-commons-xml/src/test/java/org/xwiki/xml/internal/html/DefaultHTMLCleanerTest.java
- xwiki-commons-core/xwiki-commons-xml/src/test/java/org/xwiki/xml/internal/html/HTML5HTMLCleanerTest.java
* Add a new HTML_VERSION parameter to HTMLCleanerConfiguration.
* Pass the HTML version in DefaultHTMLCleaner to HTMLCleaner and set the document type accordingly.
* Add a tag transformation to transform `<tt>` to `<span class="monospace">`.
* Add a tag transformation to replace the font filter in HTML5 as the cleaner removes the font tags too early otherwise.
* Extend BodyFilter to allow more HTML5 tags directly in the body.
* Add constants for many HTML5 tags in HTMLConstants.
* Add a new unit test HTML5HTMLCleanerTest to test the behavior of HTMLCleaner with the HTML5 configuration.
* Modify DefaultHTMLCleanerTest to allow re-using most test methods in HTML5HTMLCleanerTest.
Due to https://sourceforge.net/p/htmlcleaner/bugs/228/ and https://sourceforge.net/p/htmlcleaner/bugs/229/ there …
> XCOMMONS-901: Support both XHTML 1.0 and XHTML 5 in HtmlCleaner

- xwiki-commons-core/xwiki-commons-xml/src/main/java/org/xwiki/xml/html/HTMLCleanerConfiguration.java
- xwiki-commons-core/xwiki-commons-xml/src/main/java/org/xwiki/xml/html/HTMLConstants.java
- xwiki-commons-core/xwiki-commons-xml/src/main/java/org/xwiki/xml/html/XWikiHTML5TagProvider.java
- xwiki-commons-core/xwiki-commons-xml/src/main/java/org/xwiki/xml/internal/html/DefaultHTMLCleaner.java
- xwiki-commons-core/xwiki-commons-xml/src/test/java/org/xwiki/xml/internal/html/HTML5HTMLCleanerTest.java
* Cleanup some comments and introduce a helper to check if the configuration is HTML 5.
* Allow b, i, u and s tags in HTML 5 as they are not obsolete in HTML 5 (and i is in fact frequently used for icons).
* Add XWikiHTML5TagProvider to fix svg and style tag handling.
* Fix class fan-out complexity in DefaultHTMLCleaner by not using the CleanerTransformations class but only our subclass.
This is a follow-up on https://jira.xwiki.org/browse/XCOMMONS-901 to fix some remaining issues with HTML 5 compatibility. Per the [development practices](https://dev.xwiki.org/xwiki/bin/view/Community/DevelopmentPractices#HRule:Don27tcreateunnecessaryissues) I haven't opened a separate issue for it.
> XCOMMONS-901: Support both XHTML 1.0 and XHTML 5 in HtmlCleaner (follow-up)

- xwiki-commons-core/xwiki-commons-xml/pom.xml
- xwiki-commons-core/xwiki-commons-xml/src/main/checkstyle/checkstyle-suppressions.xml
- xwiki-commons-core/xwiki-commons-xml/src/main/java/org/xwiki/xml/html/HTMLElementSanitizer.java
- xwiki-commons-core/xwiki-commons-xml/src/main/java/org/xwiki/xml/internal/html/DefaultHTMLCleaner.java
- xwiki-commons-core/xwiki-commons-xml/src/main/java/org/xwiki/xml/internal/html/DefaultHTMLElementSanitizer.java
- xwiki-commons-core/xwiki-commons-xml/src/main/java/org/xwiki/xml/internal/html/HTMLDefinitions.java
- xwiki-commons-core/xwiki-commons-xml/src/main/java/org/xwiki/xml/internal/html/HTMLElementSanitizerConfiguration.java
- xwiki-commons-core/xwiki-commons-xml/src/main/java/org/xwiki/xml/internal/html/InsecureHTMLElementSanitizer.java
- xwiki-commons-core/xwiki-commons-xml/src/main/java/org/xwiki/xml/internal/html/MathMLDefinitions.java
- xwiki-commons-core/xwiki-commons-xml/src/main/java/org/xwiki/xml/internal/html/SVGDefinitions.java
- xwiki-commons-core/xwiki-commons-xml/src/main/java/org/xwiki/xml/internal/html/SecureHTMLElementSanitizer.java
- xwiki-commons-core/xwiki-commons-xml/src/main/java/org/xwiki/xml/internal/html/filter/SanitizerFilter.java
- xwiki-commons-core/xwiki-commons-xml/src/main/resources/META-INF/components.txt
- xwiki-commons-core/xwiki-commons-xml/src/test/java/org/xwiki/xml/html/HTMLUtilsTest.java
- xwiki-commons-core/xwiki-commons-xml/src/test/java/org/xwiki/xml/html/filter/AbstractHTMLFilterTest.java
- xwiki-commons-core/xwiki-commons-xml/src/test/java/org/xwiki/xml/internal/html/DefaultHTMLCleanerTest.java
- xwiki-commons-core/xwiki-commons-xml/src/test/java/org/xwiki/xml/internal/html/DefaultHTMLElementSanitizerTest.java
- xwiki-commons-core/xwiki-commons-xml/src/test/java/org/xwiki/xml/internal/html/HTMLElementSanitizerTest.java
- xwiki-commons-core/xwiki-commons-xml/src/test/java/org/xwiki/xml/internal/html/SecureHTMLElementSanitizerTest.java
* Add an interface and three implementations for an HTML element sanitizer.
* Let the default implementation dispatch to the different implementations depending on a configuration.
* Add tests.
Jira issue: https://jira.xwiki.org/browse/XCOMMONS-2426
> XCOMMONS-2426: Provide a component for filtering safe HTML elements and attributes

- xwiki-commons-core/xwiki-commons-velocity/src/main/java/org/xwiki/velocity/tools/JSONTool.java
- xwiki-commons-core/xwiki-commons-velocity/src/test/java/org/xwiki/velocity/tools/JSONToolTest.java
* Add custom character escapes for JSONTool that include forward slash.
Jira issue: https://jira.xwiki.org/browse/XCOMMONS-1120
> XCOMMONS-1120: JSONTool is not escaping solidus (/)

- xwiki-commons-core/xwiki-commons-xml/src/main/java/org/xwiki/xml/XMLUtils.java
- xwiki-commons-core/xwiki-commons-xml/src/test/java/org/xwiki/xml/XMLUtilsTest.java
* Escape {
* Escape > and - at the start of comments to ensure the resulting comment is valid in HTML.
Note that due do how the XML metadata comments are structured, the start of a comment will never be invalid and thus the additional fixes for > and - at the start of a comment are just there to be on the safe side for generic use, not to fix actual bugs.
I will adjust the equivalent code in [xwiki-platform-core/xwiki-platform-ckeditor/xwiki-platform-ckeditor-plugins/src/main/resources/xwiki-marker/plugin.js#L119](https://github.com/xwiki/xwiki-platform/blob/4990040521f5710f2dfee458df8ba72a88654ca5/xwiki-platform-core/xwiki-platform-ckeditor/xwiki-platform-ckeditor-plugins/src/main/resources/xwiki-marker/plugin.js#L119) after the merge of this PR to be consistent with the new …
> XCOMMONS-2586: XMLUtils#escapeXMLComment doesn't escape {

- xwiki-commons-core/xwiki-commons-extension/xwiki-commons-extension-api/src/main/java/org/xwiki/extension/repository/internal/core/DefaultCoreExtensionScanner.java
When failing to load the xed file it might be because we are trying to load the xed file for a jar file provided by the application server. Including a note in the debug message to mention this possible explanation.
> Improving debug logging

- xwiki-commons-core/xwiki-commons-blame/xwiki-commons-blame-api/src/main/java/org/xwiki/blame/internal/DefaultAnnotatedContent.java
minor: make private class final with default constructor
This is part of https://github.com/checkstyle/checkstyle/pull/12737
According to the https://docs.oracle.com/javase/specs/jls/se17/html/jls-8.html#jls-8.8.9 The default constructor has the same access modifier as the class.
and according to the check https://checkstyle.org/config_design.html#FinalClass a class that has only private constructors and has no descendant classes is declared as final.
> minor: make private class final with default constructor

- xwiki-commons-core/xwiki-commons-extension/xwiki-commons-extension-api/src/main/java/org/xwiki/extension/internal/DefaultExtensionContext.java
- xwiki-commons-core/xwiki-commons-extension/xwiki-commons-extension-api/src/main/java/org/xwiki/extension/job/history/internal/DefaultExtensionJobHistory.java
- xwiki-commons-core/xwiki-commons-xml/src/main/java/org/xwiki/xml/XMLUtils.java
- xwiki-commons-core/xwiki-commons-xml/src/main/java/org/xwiki/xml/internal/LocalEntityResolver.java
- xwiki-commons-tools/xwiki-commons-tool-test/xwiki-commons-tool-test-component/src/main/java/org/xwiki/test/jmock/AbstractMockingComponentTestCase.java
minor: make private class final with default constructor
This is part of https://github.com/checkstyle/checkstyle/pull/12737
According to the https://docs.oracle.com/javase/specs/jls/se17/html/jls-8.html#jls-8.8.9 The default constructor has the same access modifier as the class.
and according to the check https://checkstyle.org/config_design.html#FinalClass a class that has only private constructors and has no descendant classes is declared as final.
> minor: make private class final with default constructor-2

- xwiki-commons-core/xwiki-commons-extension/xwiki-commons-extension-api/src/main/java/org/xwiki/extension/job/history/internal/ReplayJob.java
- xwiki-commons-core/xwiki-commons-extension/xwiki-commons-extension-api/src/test/java/org/xwiki/extension/job/history/internal/ReplayJobTest.java
- xwiki-commons-core/xwiki-commons-job/xwiki-commons-job-api/src/main/java/org/xwiki/job/AbstractJobStatus.java
JIRA: https://jira.xwiki.org/browse/XCOMMONS-2756
Provide a setter for the parent job status in AbstractJobStatus, so that it's possible in ReplayJob to properly set the children job status' parent, without needing to rely on the context.
> XCOMMONS-2576: ReplayJob is not properly setting the parent job status of its children jobs

- xwiki-commons-core/xwiki-commons-xml/src/main/java/org/xwiki/xml/internal/html/filter/SanitizerDetectorFilter.java
- xwiki-commons-core/xwiki-commons-xml/src/main/java/org/xwiki/xml/internal/html/filter/SanitizerFilter.java
- xwiki-commons-core/xwiki-commons-xml/src/main/resources/META-INF/components.txt
- xwiki-commons-core/xwiki-commons-xml/src/test/java/org/xwiki/xml/internal/html/filter/SanitizerDetectorFilterTest.java
* Add a new filter SanitizerDetectorFilter that allows detecting if HTML content is affected by the sanitizer.
* Simplify the loop in SanitizerDetectorFilter to not exceed the complexity threshold of SonarLint.
* Add a unit test for SanitizerDetectorFilter.
Jira issue: https://jira.xwiki.org/browse/XCOMMONS-2840
> XCOMMONS-2840: Add an API in HTMLCleaner to test if content is affected by restricted cleaning

- xwiki-commons-core/xwiki-commons-extension/xwiki-commons-extension-api/src/main/java/org/xwiki/extension/repository/internal/core/DefaultCoreExtensionScanner.java
- xwiki-commons-core/xwiki-commons-extension/xwiki-commons-extension-api/src/test/java/org/xwiki/extension/repository/internal/core/DefaultCoreExtensionScannerTest.java
Jira: https://jira.xwiki.org/browse/XCOMMONS-1099
> XCOMMONS-2874: DefaultCoreExtensionScanner#loadEnvironmentExtension does not set extension url

- .mvn/gradle-enterprise.xml
- README.md
- Updated Revved up by Gradle Enterprise badge to say Revved up by Develocity (after GE -> Develocity rename)
- Updated build cache config to only push when authenticated
> Update gradle enterprise

- xwiki-commons-core/xwiki-commons-xml/src/main/java/org/xwiki/xml/XMLUtils.java
- xwiki-commons-core/xwiki-commons-xml/src/test/java/org/xwiki/xml/XMLUtilsTest.java
https://jira.xwiki.org/browse/XCOMMONS-2989
* Refactor the code to avoid too high complexity
* Refactor the test to be parameterized and add a few test cases
This is needed to fix https://jira.xwiki.org/browse/XWIKI-21868 and seems like the simplest, backwards-compatible change. An alternative would be to completely change the escaping format which would be a lot more breaking.
Built `xwiki-commons-xml` with the `quality` profile. This is very unlikely to cause any regressions as the escaping format remains unchanged.
* stable-15.10.x
> XCOMMONS-2989: Escape characters after < in XML comments

- pom.xml
- xwiki-commons-tools/xwiki-commons-tool-extension-plugin/pom.xml
- xwiki-commons-tools/xwiki-commons-tool-extension-plugin/src/main/java/org/xwiki/tool/extension/XIPMojo.java
- xwiki-commons-tools/xwiki-commons-tool-xar/xwiki-commons-tool-xar-plugin/pom.xml
- xwiki-commons-tools/xwiki-commons-tool-xar/xwiki-commons-tool-xar-plugin/src/main/java/org/xwiki/tool/xar/XARMojo.java
https://jira.xwiki.org/browse/XCOMMONS-3110
* Use MavenArchiver to parse the output timestamp.
* Use configureReproducibleBuild to configure the build to be reproducible when the output timestamp is set.
* I've decided to add MavenArchiver as a dependency as otherwise we would need to duplicate the parsing logic for the output timestamp which is entirely trivial as it supports two formats (timestamp and date string) and there is a logic to only allow a certain time range.
I've built the whole xwiki-platform with the changed plugins and at least XAR builds are reproducible now. There are other parts like the CKEditor build that aren't reproducible, so I couldn't test everything.
*  None (improvement)
> XCOMMONS-3110: Make the XIP and XAR builds reproducible

- xwiki-commons-core/xwiki-commons-cache/xwiki-commons-cache-api/pom.xml
- xwiki-commons-core/xwiki-commons-cache/xwiki-commons-cache-api/src/main/java/org/xwiki/cache/util/AbstractCache.java
- xwiki-commons-core/xwiki-commons-legacy/xwiki-commons-legacy-cache/pom.xml
- xwiki-commons-core/xwiki-commons-legacy/xwiki-commons-legacy-cache/xwiki-commons-legacy-cache-api/pom.xml
- xwiki-commons-core/xwiki-commons-legacy/xwiki-commons-legacy-cache/xwiki-commons-legacy-cache-api/src/main/aspect/org/xwiki/cache/util/AbstractCacheCompatibilityAspect.aj
https://jira.xwiki.org/browse/XCOMMONS-3174
* Move org.xwiki.cache.util.AbstractCache#AbstractCache() to legacy
* introduce the cache-api legacy module
* add the new module to the legacy-war dependencies (in a separate PR https://github.com/xwiki/xwiki-platform/pull/3573 on xwiki-platform)
Fully built xwiki-commons with the legacy flag
* N/A
> XCOMMONS-3174: Move org.xwiki.cache.util.AbstractCache#AbstractCache() to legacy

- pom.xml
- xwiki-commons-core/pom.xml
- xwiki-commons-core/xwiki-commons-xml/pom.xml
- xwiki-commons-core/xwiki-commons-xml/src/main/java/org/xwiki/xml/html/HTMLUtils.java
https://jira.xwiki.org/browse/XCOMMONS-2174
* Rewrite XML output in HTMLUtils using JDOM 2.
* Make the helper class private to not expose JDOM 2 in the API.
* Remove the dependency.
* The class that was extended in the previous version is final in JDOM 2. Further, the methods that we're overriding are now in another class. Therefore, we're extending that class instead. To not repeat the mistake of exposing a dependency's API, I've made the nested class private.
* This pull request depends on xwiki/xwiki-platform#3576 and needs a vote for the breakage.
No changes.
In `xwiki-commons` (root):
```
LANG=C.UTF-8 mvn clean install -Pdocker,legacy,integration-tests,snapshotModules,quality,distribution,flavor-integration-tests
```
* None (breaking …
> XCOMMONS-2174: Get rid of JDOM 1 dependency

- xwiki-commons-core/xwiki-commons-environment/xwiki-commons-environment-servlet/pom.xml
- xwiki-commons-core/xwiki-commons-environment/xwiki-commons-environment-servlet/src/main/java/org/xwiki/environment/internal/ServletEnvironment.java
- xwiki-commons-core/xwiki-commons-environment/xwiki-commons-environment-servlet/src/test/java/org/xwiki/environment/internal/ServletEnvironmentTest.java
https://jira.xwiki.org/browse/XCOMMONS-3258
* Introduce a dynamically initialized cache to avoid issues with recursive component initialization calls.
* Add test cases to confirm that the cache works as expected and that cache initialization can do recursive calls for getting resources.
* As the proposal at https://forum.xwiki.org/t/cache-servletcontext-getresource/16416 and the discussion yesterday didn't bring a real conclusion about introducing a "development" mode, the cache can currently be disabled with the regular `CacheControl` mechanism that we're already using for other caches. In my opinion, we should discuss improving the cache control mechanism to limit it to users with programming right as this seems to be the easiest solution without introducing any side effects.
* Without …
> XCOMMONS-3258: Introduce a cache for ServletEnvironment#getResource

- xwiki-commons-core/xwiki-commons-xml/src/main/java/org/xwiki/xml/internal/html/filter/SanitizerFilter.java
- xwiki-commons-tools/xwiki-commons-tool-verification-resources/src/main/resources/checkstyle.xml
As per upcoming changes in https://github.com/checkstyle/checkstyle/pull/16049 for [JavadocVariable](https://checkstyle.org/checks/javadoc/javadocvariable.html#JavadocVariable) check, this PR replaces scope with new accessModifiers property.
As the behavior of the check has changed to not account for the surrounding scope, some javadocs had to be added.
>[!Note]
>This PR should be merged after the release of checkstyle 10.22.0
> Checkstyle: Replaced property scope with new accessModifiers for JavadocVariable check

- xwiki-commons-core/xwiki-commons-classloader/xwiki-commons-classloader-api/pom.xml
- xwiki-commons-core/xwiki-commons-classloader/xwiki-commons-classloader-api/src/main/java/org/xwiki/classloader/internal/ClassLoaderUtils.java
- xwiki-commons-core/xwiki-commons-classloader/xwiki-commons-classloader-api/src/test/java/org/xwiki/classloader/internal/ClassLoaderUtilsTest.java
The goal of this pull request is to provide an internal helpers that prevent traversal attacks when accessing resources from the classloader.
The pull request comes with unit tests.
* Backport on branches: 16.4.x, 16.10.x
> XCOMMONS-3327: Provide an internal helper to safely access ClassLoader resources

- xwiki-commons-core/xwiki-commons-configuration/pom.xml
- xwiki-commons-core/xwiki-commons-configuration/xwiki-commons-configuration-api/src/main/java/org/xwiki/configuration/ConfigurationSource.java
- xwiki-commons-core/xwiki-commons-configuration/xwiki-commons-configuration-api/src/main/java/org/xwiki/configuration/internal/AbstractCompositeConfigurationSource.java
- xwiki-commons-core/xwiki-commons-configuration/xwiki-commons-configuration-api/src/main/java/org/xwiki/configuration/internal/AbstractConfigurationSource.java
- xwiki-commons-core/xwiki-commons-configuration/xwiki-commons-configuration-api/src/main/java/org/xwiki/configuration/internal/CompositeConfigurationSource.java
- xwiki-commons-core/xwiki-commons-configuration/xwiki-commons-configuration-api/src/main/java/org/xwiki/configuration/internal/ConfigurationSourceDecorator.java
- xwiki-commons-core/xwiki-commons-configuration/xwiki-commons-configuration-api/src/main/java/org/xwiki/configuration/internal/MapConfigurationSource.java
- xwiki-commons-core/xwiki-commons-configuration/xwiki-commons-configuration-api/src/main/java/org/xwiki/configuration/internal/MemoryConfigurationSource.java
- xwiki-commons-core/xwiki-commons-configuration/xwiki-commons-configuration-api/src/main/java/org/xwiki/configuration/internal/VoidConfigurationSource.java
- xwiki-commons-core/xwiki-commons-configuration/xwiki-commons-configuration-default/pom.xml
- xwiki-commons-core/xwiki-commons-configuration/xwiki-commons-configuration-default/src/main/java/org/xwiki/configuration/internal/AbstractPropertiesConfigurationSource.java
- xwiki-commons-core/xwiki-commons-configuration/xwiki-commons-configuration-default/src/main/java/org/xwiki/configuration/internal/AbstractSystemOverwriteConfigurationSource.java
- xwiki-commons-core/xwiki-commons-configuration/xwiki-commons-configuration-default/src/main/java/org/xwiki/configuration/internal/SystemConfigurationSource.java
- xwiki-commons-core/xwiki-commons-configuration/xwiki-commons-configuration-default/src/main/java/org/xwiki/configuration/internal/SystemEnvConfigurationSource.java
- xwiki-commons-core/xwiki-commons-configuration/xwiki-commons-configuration-default/src/main/java/org/xwiki/configuration/internal/SystemPropertiesConfigurationSource.java
- xwiki-commons-core/xwiki-commons-configuration/xwiki-commons-configuration-default/src/main/resources/META-INF/components.txt
- xwiki-commons-core/xwiki-commons-configuration/xwiki-commons-configuration-default/src/test/java/org/xwiki/configuration/internal/SystemEnvConfigurationSourceTest.java
- xwiki-commons-core/xwiki-commons-configuration/xwiki-commons-configuration-default/src/test/java/org/xwiki/configuration/internal/SystemOverwriteConfigurationSourceTest.java
- xwiki-commons-core/xwiki-commons-configuration/xwiki-commons-configuration-default/src/test/java/org/xwiki/configuration/internal/SystemPropertiesConfigurationSourceTest.java
- xwiki-commons-core/xwiki-commons-extension/xwiki-commons-extension-api/src/main/java/org/xwiki/extension/internal/DefaultExtensionManagerConfiguration.java
The `xwiki-platform` side of things can be reviewed on https://github.com/xwiki/xwiki-platform/pull/4069.
https://jira.xwiki.org/browse/XCOMMONS-3289
The idea is to allow overwriting any `xwiki.cfg` and `xwiki.properties` values through environment variable or Java system properties. In practice, it means new System properties and environment oriented ConfigurationSource were introduces, and they should be used in any ConfigurationSource which would like to allow being overwritten by system properties and env variables.
I also added new `ConfigurationSource#getKeys(String prefix)` and `isEmpty(String prefix)` APIs, which are mainly helpers to directly get keys starting with a specific prefix.
See https://forum.xwiki.org/t/add-a-generic-way-to-overwrite-some-configuration-through-environmen …
> XCOMMONS-3289: Allow overwritting xwiki.properties and xwiki.cfg properties via environment variable and Java system properties

- xwiki-commons-core/xwiki-commons-properties/src/main/java/org/xwiki/properties/PropertyDescriptor.java
- xwiki-commons-core/xwiki-commons-properties/src/main/java/org/xwiki/properties/annotation/PropertyOrder.java
- xwiki-commons-core/xwiki-commons-properties/src/main/java/org/xwiki/properties/internal/DefaultBeanDescriptor.java
- xwiki-commons-core/xwiki-commons-properties/src/main/java/org/xwiki/properties/internal/DefaultPropertyDescriptor.java
- xwiki-commons-core/xwiki-commons-properties/src/test/java/org/xwiki/properties/internal/DefaultBeanDescriptorTest.java
- xwiki-commons-core/xwiki-commons-properties/src/test/java/org/xwiki/properties/test/TestBean.java
https://jira.xwiki.org/browse/XCOMMONS-1258
* Provide new annotation for property ordering
* Provide needed getters/setters and parsing of the annotation
* This work is not yet used: it will need some work in xwiki-platform to be used.
mvn clean install -Pquality in impacted module
* None
> XCOMMONS-1258: Allow parameters of rendering macro developed in Java to be ordered

- xwiki-commons-core/xwiki-commons-environment/xwiki-commons-environment-servlet/pom.xml
- xwiki-commons-core/xwiki-commons-environment/xwiki-commons-environment-servlet/src/main/java/org/xwiki/environment/internal/ServletEnvironment.java
- xwiki-commons-core/xwiki-commons-environment/xwiki-commons-environment-servlet/src/main/java/org/xwiki/environment/internal/ServletEnvironmentCacheInitializer.java
- xwiki-commons-core/xwiki-commons-environment/xwiki-commons-environment-servlet/src/main/resources/META-INF/components.txt
- xwiki-commons-core/xwiki-commons-environment/xwiki-commons-environment-servlet/src/test/java/org/xwiki/environment/internal/ServletEnvironmentCacheInitializerTest.java
- xwiki-commons-core/xwiki-commons-environment/xwiki-commons-environment-servlet/src/test/java/org/xwiki/environment/internal/ServletEnvironmentTest.java
https://jira.xwiki.org/browse/XCOMMONS-3348
* Trigger the cache initialization in a separate event listener on the ApplicationStartedEvent. This ensures that the cache manager is ready.
* Add and adapt unit tests.
Other options considered:
* Change the configuration to read the resource as stream to not trigger the cache - this seems like a hack and will break the moment we use the cache to avoid slow running time for missing resources requested as stream.
* Just suppress the exception. This doesn't seem like a clean solution, either, exceptions should be exceptional and not expected.
No UI changes.
Built `xwiki-commons-environment-servlet` with quality profile. Executed an integration test to verify that the log about the cycle is gone.
* …
> XCOMMONS-3348: The servlet environment triggers a second load of the xwiki.properties configuration

- pom.xml
- xwiki-commons-core/xwiki-commons-extension/xwiki-commons-extension-handlers/xwiki-commons-extension-handler-jar/src/main/java/org/xwiki/extension/jar/internal/handler/JarExtensionHandler.java
- xwiki-commons-core/xwiki-commons-extension/xwiki-commons-extension-handlers/xwiki-commons-extension-handler-jar/src/main/java/org/xwiki/extension/jar/internal/handler/JarExtensionJobFinishingListener.java
- xwiki-commons-core/xwiki-commons-extension/xwiki-commons-extension-handlers/xwiki-commons-extension-handler-jar/src/main/java/org/xwiki/extension/jar/internal/handler/WebjarNodeArtifactTypeConverter.java
- xwiki-commons-core/xwiki-commons-extension/xwiki-commons-extension-handlers/xwiki-commons-extension-handler-jar/src/main/resources/META-INF/components.txt
- xwiki-commons-core/xwiki-commons-extension/xwiki-commons-extension-repositories/xwiki-commons-extension-repository-maven/src/main/resources/META-INF/plexus/components.xml
- xwiki-commons-tools/pom.xml
- xwiki-commons-tools/xwiki-commons-tool-webjar-node-handlers/pom.xml
- xwiki-commons-tools/xwiki-commons-tool-webjar-node-handlers/src/main/resources/META-INF/plexus/components.xml
https://jira.xwiki.org/browse/XCOMMONS-3349
* Introduces a new maven extension handler `webjar-node` dedicated to projects relying on node to produce webjars.
TODO:
N/A
see https://github.com/xwiki/xwiki-platform/pull/4206
I rebuild `xwiki-platform-livedata-webjar` and compared it to a preview version. The contents are identical.
* N/A
> XCOMMONS-3349: Make it easier to create webjar modules using node

- xwiki-commons-core/xwiki-commons-job/xwiki-commons-job-api/src/main/java/org/xwiki/job/JobExecutor.java
- xwiki-commons-core/xwiki-commons-job/xwiki-commons-job-default/src/main/java/org/xwiki/job/internal/DefaultJobExecutor.java
https://jira.xwiki.org/browse/XCOMMONS-3330
* Store several current jobs.
* Add a new possibility to return all running jobs of a job group.
* Deprecate the old method that returns just a single running job.
* Clean up empty entries in groupedJobs.
* Some code cleanup.
* This needs more testing, in particular in automated tests.
No UI changes.
```
mvn clean install -Pintegration-tests,docker,legacy,quality -pl :xwiki-commons-job-api,:xwiki-commons-job-default
```
* Not sure, we could decide to backport this.
> XCOMMONS-3330: Job groups with several threads may not return a current job

- pom.xml
- xwiki-commons-core/xwiki-commons-velocity/src/main/java/org/xwiki/velocity/tools/StringTool.java
- xwiki-commons-core/xwiki-commons-velocity/src/test/java/org/xwiki/velocity/tools/StringToolTest.java
https://jira.xwiki.org/browse/XCOMMONS-3382
* Un-deprecate the newly deprecated methods as we offer no alternative in Velocity, and the new Strings API seems very confusing so far as it's inconsistent which methods are in `Strings` and which are still in `StringUtils`.
* I've copied the documentation to have nice documentation in the scripting API.
* This is a security update. The security vulnerability shouldn't really affect XWiki, but it's still better to upgrade in case an extension is using one of the vulnerable methods. For this reason, it should also be backported on the LTS branches.
No UI changes.
```
mvn clean install -Pquality,legacy -pl :xwiki-commons,:xwiki-commons-velocity,:xwiki-commons-legacy-velocity
```
* stable-17.4.x
* …
> XCOMMONS-3382: Upgrade to commons-lang3 3.18.0
