xwiki-commons-core/xwiki-commons-filter/xwiki-commons-filter-streams/xwiki-commons-filter-stream-xml/src/main/java/org/xwiki/filter/filterxml/internal/input/XMLInputFilterFactory.java

Modify description of the input filter

---

xwiki-commons-tools/xwiki-commons-tool-verification-resources/src/main/resources/checkstyle.xml

In future will be added support annotation, import and implements.

Added annotations in excludedClasses for ClassFanOutComplexity

---

xwiki-commons-core/xwiki-commons-xml/pom.xml
xwiki-commons-core/xwiki-commons-xml/src/main/java/org/htmlcleaner/XWikiDOMSerializer.java

I just had to change the import to a different class. The method calls stay the same
As part of the Replace calls to deprecated APIs by more up to date alternatives Task

Replaced call to old API

---

xwiki-commons-core/xwiki-commons-velocity/pom.xml
xwiki-commons-core/xwiki-commons-velocity/src/main/java/org/xwiki/velocity/tools/EscapeTool.java

As Part of Replace calls to deprecated APIs by more up to date alternatives

Added Call to Newer API

---

xwiki-commons-core/xwiki-commons-component/xwiki-commons-component-api/src/main/java/org/xwiki/component/descriptor/DefaultComponentDependency.java
xwiki-commons-core/xwiki-commons-component/xwiki-commons-component-default/src/test/java/org/xwiki/component/ProviderTest.java

For task "Replace calls to deprecated APIs by more up to date alternatives "

Change usages of DefaultComponentRole<T>'s setRole to setRoleType

---

xwiki-commons-core/xwiki-commons-displayer/src/main/java/org/xwiki/displayer/HTMLDisplayer.java
xwiki-commons-core/xwiki-commons-displayer/src/main/java/org/xwiki/displayer/internal/DefaultHTMLDisplayer.java
xwiki-commons-core/xwiki-commons-displayer/src/main/java/org/xwiki/displayer/internal/DefaultHTMLDisplayerManager.java
xwiki-commons-core/xwiki-commons-displayer/src/main/resources/META-INF/components.txt
xwiki-commons-core/xwiki-commons-displayer/src/test/java/org/xwiki/displayer/HTMLDisplayerManagerTest.java

https://jira.xwiki.org/browse/XCOMMONS-1527
* Improve the implementation of the default HTMLDisplayerManager.
* Adapt and refactor the tests.

XCOMMONS-1527: Create an HTML Displayer interface

---

xwiki-commons-core/xwiki-commons-properties/pom.xml
xwiki-commons-core/xwiki-commons-properties/src/main/java/org/xwiki/properties/PropertyDescriptor.java
xwiki-commons-core/xwiki-commons-properties/src/main/java/org/xwiki/properties/PropertyGroupDescriptor.java
xwiki-commons-core/xwiki-commons-properties/src/main/java/org/xwiki/properties/annotation/PropertyFeature.java
xwiki-commons-core/xwiki-commons-properties/src/main/java/org/xwiki/properties/internal/DefaultBeanDescriptor.java
xwiki-commons-core/xwiki-commons-properties/src/main/java/org/xwiki/properties/internal/DefaultPropertyDescriptor.java
xwiki-commons-core/xwiki-commons-properties/src/test/java/org/xwiki/properties/internal/DefaultBeanDescriptorTest.java
xwiki-commons-core/xwiki-commons-properties/src/test/java/org/xwiki/properties/internal/converter/ArrayListConverterTest.java
xwiki-commons-core/xwiki-commons-properties/src/test/java/org/xwiki/properties/test/TestBean.java

https://jira.xwiki.org/browse/XCOMMONS-1530
* Create a PropertyFeature annotation.
* Add an feature field in the PropertyDescriptor.
* Add related tests.

XCOMMONS-1530: Add support for feature parameters in property descriptors

---

xwiki-commons-core/xwiki-commons-component/xwiki-commons-component-default/src/main/java/org/xwiki/component/embed/EmbeddableComponentManager.java

Here is a pull request for the patch in https://jira.xwiki.org/browse/XWIKI-15978.

XWIKI-15978: Make shutdown much faster by optimizing sorting of component dependencies in dispose()

---

xwiki-commons-core/xwiki-commons-xml/pom.xml
xwiki-commons-core/xwiki-commons-xml/src/main/checkstyle/checkstyle-suppressions.xml
xwiki-commons-core/xwiki-commons-xml/src/main/java/org/htmlcleaner/XWikiDOMSerializer.java
xwiki-commons-core/xwiki-commons-xml/src/test/java/org/xwiki/xml/internal/html/DefaultHTMLCleanerTest.java

https://jira.xwiki.org/browse/XCOMMONS-1553
* Remove XWikiDOMSerializer, use HtmlCleaner DomSerializer and fix
tests accordingly.

XCOMMONS-1553: Remove XWikiDOMSerializer in favor of HtmlCleaner DomSerializer

---

xwiki-commons-core/xwiki-commons-observation/xwiki-commons-observation-local/src/main/java/org/xwiki/observation/internal/DefaultObservationManager.java

* Add synchronized blocks around add/remove of listeners

XWIKI-16036: Random warning log - Could not find any matching step

---

xwiki-commons-core/xwiki-commons-properties/src/main/java/org/xwiki/properties/PropertyDescriptor.java
xwiki-commons-core/xwiki-commons-properties/src/main/java/org/xwiki/properties/annotation/PropertyAdvanced.java
xwiki-commons-core/xwiki-commons-properties/src/main/java/org/xwiki/properties/annotation/PropertyFeature.java
xwiki-commons-core/xwiki-commons-properties/src/main/java/org/xwiki/properties/annotation/PropertyGroup.java

Should be backported in 10.11 if merged.

[Misc] Add missing unstable annotations

---

xwiki-commons-core/xwiki-commons-xml/pom.xml
xwiki-commons-core/xwiki-commons-xml/src/test/java/org/xwiki/xml/html/filter/AbstractHTMLFilterTest.java

* Add a new test class for AbstractHTMLFilter

[Misc] Fix mutation threshold in commons-xml

---

xwiki-commons-core/xwiki-commons-xml/src/main/java/org/xwiki/xml/html/HTMLUtils.java
xwiki-commons-core/xwiki-commons-xml/src/test/java/org/xwiki/xml/internal/html/DefaultHTMLCleanerTest.java

- Fix the pattern to recognize entities
- Add one more test

HTMLCleaner doesn't recognize some HTML named entity

---

xwiki-commons-core/xwiki-commons-extension/xwiki-commons-extension-api/src/main/java/org/xwiki/extension/repository/internal/installed/AbstractInstalledExtensionRepository.java

* Fix proposal for the stackoverflow

XWIKI-16930: Stack overflow on "Orphaned dependencies"

---

xwiki-commons-tools/xwiki-commons-tool-verification-resources/pom.xml

to not conflict with checkstyle's version
library will be introduced at https://github.com/checkstyle/checkstyle/pull/8743

[misc] exclude org.reflections dependency from checkstyle 

---

xwiki-commons-core/xwiki-commons-xml/src/main/java/org/xwiki/xml/XMLUtils.java
xwiki-commons-core/xwiki-commons-xml/src/test/java/org/xwiki/xml/XMLUtilsTest.java

https://jira.xwiki.org/browse/XCOMMONS-2016

XCOMMONS-2016: Add a new escape method that only escape the minimal amount of XML special characters

---

xwiki-commons-core/xwiki-commons-xml/src/main/java/org/xwiki/xml/internal/DefaultXMLReaderFactory.java

Configures the `XMLReader` to prevent DoS attacks:
- For _Xerces-j_, creates a `SecurityManager` with the default limits (which seem reasonable).
- For other parsers, including the _Xerces-j_ fork that ships with the JDK, it sets `FEATURE_SECURE_PROCESSING` which has the bonus of configuring properties like `http://javax.xml.XMLConstants/property/accessExternalDTD`.

XCOMMONS-2026: DefaultXMLReaderFactory creates XMLReader instances with unsafe configuration

---

xwiki-commons-core/xwiki-commons-extension/xwiki-commons-extension-repositories/xwiki-commons-extension-repository-maven/src/main/java/org/xwiki/extension/repository/aether/internal/AetherExtensionRepository.java

Fixing sonar issue - https://sonarcloud.io/project/issues?id=org.xwiki.commons%3Axwiki-commons&issues=AWgZSTOWUMkE2J58eTTL&open=AWgZSTOWUMkE2J58eTTL

sonar issue java:S1117 - Local variables should not shadow class fields

---

xwiki-commons-core/xwiki-commons-xml/src/main/java/org/xwiki/xml/html/HTMLUtils.java
xwiki-commons-core/xwiki-commons-xml/src/main/java/org/xwiki/xml/internal/html/DefaultHTMLCleaner.java
xwiki-commons-core/xwiki-commons-xml/src/test/java/org/xwiki/xml/internal/html/DefaultHTMLCleanerTest.java

Jira issue: https://jira.xwiki.org/browse/XCOMMONS-2568

XCOMMONS-2568: Improve comment handling in HTMLCleaner

---

xwiki-commons-core/xwiki-commons-xml/pom.xml
xwiki-commons-core/xwiki-commons-xml/src/main/java/org/xwiki/xml/html/script/HtmlScriptService.java
xwiki-commons-core/xwiki-commons-xml/src/test/java/org/xwiki/xml/html/script/HtmlScriptServiceTest.java

* Add a new generic HtmlScriptService which integrates API for sanitizer
* Add related unit test

XCOMMONS-2607: Add a script service for HtmlElementSanitizer

---

xwiki-commons-core/xwiki-commons-xml/src/test/java/org/xwiki/xml/XMLUtilsTest.java

Changed the comparison from equal strings to regex match.

Solution for XCOMMONS-2858.

---

xwiki-commons-tools/xwiki-commons-tool-verification-resources/src/main/resources/checkstyle.xml

None
*  Exclude Initializable, Disposable and InitializationException
*
*

[Misc] Add missing exclusions in checkstyle

---

xwiki-commons-core/xwiki-commons-extension/xwiki-commons-extension-api/src/main/java/org/xwiki/extension/repository/internal/local/LocalExtensionStorage.java

This is a work in progress related to #1160
I'm opening the PR to track comments and feedback.

Attempt of using `java.nio.file` for extension removal

---

xwiki-commons-core/xwiki-commons-velocity/src/main/java/org/xwiki/velocity/internal/InternalVelocityEngine.java

https://jira.xwiki.org/browse/XCOMMONS-3256
* Store the field as a static field to avoid the runtime overhead of repeated getting the field.
* The class that holds the field isn't accessible so accessing that class directly is no option.
No UI changes.
```
LANG=C.UTF-8 mvn clean install -Pdocker,legacy,integration-tests,snapshotModules,quality,distribution,flavor-integration-tests,standalone
```
Tested it in a running instance and `org.xwiki.velocity.internal.InternalVelocityEngine#cleanIntrospectionCache` doesn't contribute to the running time anymore according to the profiler as expected.
* stable-16.10.x

XCOMMONS-3256: Cleaning the Velocity introspection cache is expensive

---

xwiki-commons-tools/xwiki-commons-tool-verification-resources/src/main/resources/codestyle-idea.xml

[Misc] add import order for jakarta
